language: python

python:
  - "3.5"
  - "3.6"
  - "3.5-dev"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly" # currently points to 3.7-dev

install:
  - python setup.py install
  - pip install coverage

script:
  - nosetests -v --with-coverage --cover-package=racedata

after_success:
   - bash <(curl -s https://codecov.io/bash)
